### ISSUE TITLE
Bug when uninstalling the selected icon pack

### ISSUE THREAD

**Issue by drewski-00h** [falzonv/discreet-launcher#56] opened 2021-05-20 15:46 UTC
I was experimenting with icon packs today. I uninstalled the icon pack without switching back to default in the settings.  Attached is the result.  Not sure if this is a bug or normal behavior.  Force stopping Discreet Launcher fixes it.
![Screenshot_20210520-104215](https://user-images.githubusercontent.com/83047636/119009217-84ba6200-b958-11eb-8b76-1fc499272271.png)

**Comment by falzonv** [comment] 2021-05-20 21:26
Hello,

That is indeed quite unexpected, thank you for the bug report!
For now I have no idea how it could produce this strange result, will have to investigate further...

Before force stopping, did you tried to refresh the applications list?

Best regards.

**Comment by drewski-00h** [comment] 2021-05-20 21:47
The favorites drawer doesn't produce the app menu, when trying again.  Thanks!

**Comment by falzonv** [comment] 2021-05-20 22:37
Ok, I was able to reproduce the bug and after many tests I start to understand better...
This bug was present since v3.0.0, nice found!

- So indeed the bug happens only when uninstalling an "in use" icon pack.
- Before v3.4.0, only the icons from the complete list were duplicated, not the icons from the favorites panel.
- Since v3.4.0 it happens with all icons, both from the favorites panel and the complete applications list.
  - This makes the favorites drawer so big that the menu button can be off the screen and not visible, as you experimented (as per ticket #19, there is a max number of favorites according to screen size, but here the bug doubles the favorites).
- Refreshing the applications list (when the button is accessible) or restarting the launcher (as you did) solves the issue.

The reason why this strange behavior happens is still not clear to me, probably changes from v3.4.0 can gives some clues (but it is more than midnight in France so I will continue investigations another day :joy:).

Best regards.

**Comment by falzonv** [comment] 2021-06-19 07:05
Hello,

I am pleased to inform you that this should be solved in new release v4.1.0!
This release has been published a few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment] 2021-06-26 08:30
Since Thursday, release v4.1.0 is available on F-Droid so I will close this ticket.
Feel free to add comments if needed or wished.

**Closed by falzonv** 2021-06-26 08:30 UTC
Labels: bug, solved
