### ISSUE TITLE
folder freeze in some cases

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#46] opened 2021-05-13 11:59 UTC
https://user-images.githubusercontent.com/67331785/118122552-663cef80-b3c9-11eb-8d17-7ccddf8fd5fb.mp4

sometimes folder freeze and need kill the launcher

**Comment by falzonv** [comment] 2021-05-16 19:06
Thank you for the bug report and video!
I was able to reproduce the issue and will check how to correct it.

Waiting for the fix, there is no need to kill anything: you can simply tap above or below the folder popup to hide it.

To be honest I am always surprised to see how often you kill apps, or maybe you do it only for Discreet Launcher?
Except when disabling some bloatware coming with my phone, I do not even remember the last time I had to manually kill an application, it was probably a long time ago...

**Comment by xi7** [comment] 2021-05-16 19:29
the folder freeze and tap above or bellow no work. need kill the app or never back to homescreen

**Comment by xi7** [comment] 2021-05-16 20:25
https://user-images.githubusercontent.com/67331785/118411418-d027f400-b66a-11eb-985b-3fa30a6da7b8.mp4

folder freeze no work need kill the launcher.

**Comment by falzonv** [comment] 2021-05-18 15:51
Oh that is weird, when reproducing the same steps than in your video I am able to close the popup normally...
Do you also have the freeze with the classic direction of the interface? (when testing both directions I have no freeze)
Is the Back button working to close the popup?

Anyway, I changed the way folders are automatically closed and this problem should not appear anymore in future release v3.6.0.

**Comment by xi7** [comment] 2021-05-19 11:21
no, the folder freeze and continue working but never close it.

**Comment by xi7** [comment] 2021-05-19 11:29
why the folder have a lot pop up new folder ?

other detail each folder have different size view.

same old microsoft windows click folder jump other folder....

**Comment by falzonv** [comment] 2021-05-19 17:36
Hello,

I am pleased to inform you that new release v3.6.0 has been published and should solve this issue!

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment] 2021-05-23 17:12
Since today v3.6.0 is available on F-Droid, I will close this ticket.

**Closed by falzonv** 2021-05-23 17:12 UTC
Labels: bug, solved
