### ISSUE TITLE
Automatically update the list when applications are added or removed

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#10] opened 2021-03-20 12:55 UTC
https://user-images.githubusercontent.com/67331785/111870233-3ee61b00-8962-11eb-93c4-cd605d4ed674.mp4

never update list grid view

**Comment by falzonv** [comment] 2021-03-20 15:01
Hello,

There are two different things here :

1/ It is the expected behavior for now that the applications list is not updated automatically (check the text in the Settings/Help section). However, this may be improved soon and we will keep this ticket for follow-up, see more details below.

2/ Normally the launcher should not crash when opening an uninstalled or disabled application (it should only display a warning).
It is a bug introduced since v1.1.0 and I created new issue #12 to follow this.

---

About the update of the list, this is not done automatically because it would take too much resources to compute the whole list each time the applications drawer is launched.

However, while working on ticket #8, I discovered a way to listen and react to some system events. It could be used to listen for packages changes and update the list (either partial or complete update) when this happens.

This will probably take some time to implement but I will think about it and keep you updated.

Best regards.

**Comment by falzonv** [comment] 2021-03-21 13:42
Hello,

Finally it was quicker than I though, and also the occasion to make large improvements in the code structure.

Automatic update when an application is added or removed has been added in release v2.0.0 which has been pushed to GitHub few minutes ago.
**Please note that it usually takes 4 to 5 days to be fully replicated in the F-Droid repository** (automatic process).

Best regards.

---

**Remark for tickets #5, #7, #8 and #12**
Since v1.3.0 and v1.3.1 were not yet discovered by F-Droid, there is a high chance that the next release in the repository will jump directly to this new version v2.0.0 (integrates all intermediates updates).

**Comment by xi7** [comment] 2021-03-21 16:00
hi, possible upload  any link temporary?, 5 days very long :( i still using 1.2.0

https://uploadking.net/

**Comment by falzonv** [comment] 2021-03-21 19:05
Hello,

Yes because there are many recent changes, but please note that I will not do this systematically.
I agree that the process is long, but keep in mind that all of this (F-Droid store and applications, developing new releases, ...) is provided for free so not everything can be perfect.

Here is a temporary link: https://file.re/2021/03/21/discreet-launcherv200/
*(I tried to use the site you provided but register is mandatory to get a download URL. Found this other site where the file is deleted after 24h and there is no need to register.)*

**Important remarks:**
- You will probably need to uninstall the F-Droid version before being able to install the APK version (this is because F-Droid is applying its own signature and the APK has a different signature).
During the reinstall process, the favorites applications list will be lost (Android cleans everything when uninstalling).
- When you will want the F-Droid updates again, you will need to do the reinstall again in the other direction (uninstall the APK version and install the F-Droid version), and again the favorites list and other settings will be lost during uninstall.

Best regards.

**Comment by xi7** [comment] 2021-03-21 20:29
sometimes no work the refresh list, need kill the app or never refresh v2.0.0

https://user-images.githubusercontent.com/67331785/111919841-b56e4000-8a6a-11eb-89f9-fec531367cec.mp4

**Comment by falzonv** [comment] 2021-03-21 21:37
> sometimes no work the refresh list

Ok, thank you for the test and bug report.

I think this is because the events receiver is located with the complete applications list (because most of the time users will open their store from this list or uninstall an application which is not in their favorites).
This afternoon I made a dozen of install/remove to test and they were all working fine but none was launch from the home screen (each time I first opened F-Droid from the complete list), interesting test and indeed it doesn't work in this case.

I will correct this (created ticket #13 for follow-up) but it will probably not be before a few days because I do this on my spare time and next week will be quite busy.
Hopefully this is not a major bug as it should work normally from the drawer and there is always the refresh button (see below).

> need kill the app or never refresh

You do not need to kill the app to manually refresh the list, simply press the first button in the menu which is called "Refresh the applications list" (see behavior details in the integrated Help).
Of course kill and restart the app will also work but I find it simpler to press a button, up to you...

Best regards.

**Comment by falzonv** [comment] 2021-03-27 14:50
Hello,

Since today release v2.1.0 is finally available on F-Droid.
This automatic update feature was implemented in v2.0.0 and the bug from #13 is now corrected in v2.1.0.

I will close this ticket but feel free to add any comments if you want.

Best regards.

**Closed by falzonv** 2021-03-27 14:50 UTC
Labels: feature/improvement request, solved
