### ISSUE TITLE
add follow me favorite bar by notification

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#11] opened 2021-03-20 13:29 UTC
here need back to home screen and run new app
https://user-images.githubusercontent.com/67331785/111871163-88853480-8967-11eb-9aca-6b1feaba9f31.mp4

**here by notification the favorite have efficient and possible jump between apps withou back to home.**
https://user-images.githubusercontent.com/67331785/111871179-9935aa80-8967-11eb-927c-3dda8c7e0ead.mp4

**Comment by falzonv** [comment] 2021-03-20 14:34
Hello,

Seems like a good idea!
I will think about how to do it and keep you updated.

Best regards.

**Comment by falzonv** [comment] 2021-03-27 14:48
Hello,

A new notification menu has been added in release v2.1.0 which is now available on F-Droid since today.
=> See screenshot below.

This is a bit different than in your video:
- It uses buttons instead of icons because icons were not looking good on all Android versions from 5 to 11 (too small on some versions, too big on others). Buttons are better integrated in all versions and also make the notification lighter to load.
- Android limits the number of buttons to 3 on a notification.
- Every application (favorite or not) can be selected for a button in the Settings and they can be arranged in any order.

Thank you again for the idea !

Since this feature is now implemented, I will close this ticket but feel free to add comments if you want.

**Notification menu allowing quick access to 3 user-defined applications**
![2021-03-27_notification_menu](https://user-images.githubusercontent.com/4698531/112724448-b6441d80-8f13-11eb-83be-12f47777ff4f.jpg)

Best regards.

**Comment by xi7** [comment] 2021-04-27 22:49
https://user-images.githubusercontent.com/67331785/116321732-fdcafd00-a790-11eb-8a5a-ec15465f1db4.mp4

it would be possible to implement something different in the notification?
need swipe, by name looks strange, limited by 3 and cant be transparence

**Comment by falzonv** [comment] 2021-04-29 07:08
Hello,

It is probably possible because your video shows another launcher doing it.

For now, I don't know how to do the same and the closest I found was using buttons (Android limits to 3 buttons per notification).
Agree that it could look better, I will try again to find a better way (created ticket #31 for follow-up).

*Note: being quite busy currently, I will probably not start to work on it before at least one week*

Best regards.

**Comment by falzonv** [comment] 2021-04-29 20:04
I had created a new ticket but this is better for follow-up to reopen this one.

**Comment by xi7** [comment] 2021-05-01 21:17
https://user-images.githubusercontent.com/67331785/116795109-f2394800-aaa8-11eb-840f-4c7e567ef083.mp4


what about use a box transparent with favotires and by notificiation enable/disable ?

**Comment by falzonv** [comment] 2021-05-04 16:33
Hello,

Thank you for this other suggestion :-)
I was not able to do it like this, but it gave me a similar idea which works and looks quite better than the current notification:

When the user clicks on the notification, it will display something like a folder but with the favorites (see screenshot below).
Clicking outside of the box closes it and comes back to the initial application.

*(example after a click on the notification while using the calculator)*
![2021-05-04_notification_favorites](https://user-images.githubusercontent.com/4698531/117034132-4a6b8680-ad03-11eb-958d-0db2cf583638.jpg)

After many tries today, I will replace the current notification with this in the next release v3.3.0.
In addition to being better from user point of view, it will also simplify many things in the code because the current notification is in fact quite complicated to manage internally.

---

There is only one issue that I have to fix before this to be ready: sometimes the initial application is minimized and the favorites are displayed above the home screen. In this case, there is no direct return to the initial application :-/

Most of the time it works as expected (favorites are displayed above the initial application) so the issue is not easy to reproduce or understand, but I would like to solve this before publishing the release.

Best regards.

**Comment by AeOeAa** [comment] 2021-05-04 16:41
I'm looking forward to try it out 👍😀

As a bonus, it will solve a problem I have been struggling with - keeping the notification alive. Oftentimes it is gone when I need the shortcut, only returning after I open the DL menu.

**Comment by falzonv** [comment] 2021-05-04 21:09
After further tries, the issue I observed may in fact be related to the development environment.
It does not seem to happen when using the application outside of debug mode, quite strange...
=> I will publish the release like this and we will see if other people are facing the issue.

**Comment by xi7** [comment] 2021-05-04 22:23
![Screenshot_2021-05-04-19-19-36](https://user-images.githubusercontent.com/67331785/117077095-dd112300-ad0d-11eb-8662-363b6cebb148.png)

plz update remove the padding/margins between icon and text, need a lot space area screen

**Comment by AeOeAa** [comment] 2021-05-05 05:44
I noticed this too, @xi7. It's especially clear when you have more lines of icons, then padding varies between lines of apps which looks odd.

My two cents:

It happens because of line break in the text below one or more of the icon(s) horisontal. Then the other icons with just one line of text will be moved down, appearing to have more padding between icon and text.

For me, it happens more frequently with folder names because of the design choice of adding " (#)" to all titles, where # is the number of apps in the folder. I shortened some titles because of this. (renaming apps is probably not doable for most users, so there's no solution there)

Are the labels aligned center to other labels, @falzonv?

**Comment by falzonv** [comment] 2021-05-05 16:31
Hello,

Ok to improve this, this will be followed in ticket #31 (see my answer there).

Best regards.

**Comment by xi7** [comment] 2021-05-05 21:26
https://user-images.githubusercontent.com/67331785/117210920-b9fa7800-adce-11eb-8a79-6ac5c38f743f.mp4

who more efficient more productivity and elegant ?  
-access by notification
**-acess by float** 

tell me what u think :)  the idea can be auto float while out home

**Comment by falzonv** [comment] 2021-05-06 16:48
Hello,

This is a very subjective question :-)
If we compare the float to the former notification with buttons, I prefer the float.
But now if we compare the float to the new notification from v3.3.0, I prefer the notification.

---

After further checking, adding the float would require the permission to draw over other applications.
Unfortunately, this permission is protected by Android and only the system itself or phone vendors can have it...

> Extract from [Android documentation](https://developer.android.com/guide/topics/permissions/overview#special):
*"Special permissions correspond to particular app operations. Only the **platform and OEMs can define special permissions**. Additionally, the platform and OEMs usually define special permissions when they want to protect access to particularly powerful actions, **such as drawing over other apps**."*

Best regards.

**Comment by xi7** [comment] 2021-05-06 17:34
I'm waiting for the fdroid publish v3.3.0 , possible upload temporarily 3.3.0 ?

tell me about:

-need swipe sometimes ?
-others apps may can override the priority on the bar ?
-after many notifications, can it be difficult to find list?
-transparent bar ?

after the favorites follow users, would there be a need to keep the old favorite homescreen?

-old homescreen = yes
-by notification v3.2.0 = yes

float can be high efficent many scenarios, 1click shows in any situation.

**Comment by falzonv** [comment] 2021-05-06 19:45
> possible upload temporarily 3.3.0 ?

Yes because of the new notification, but please note that I will not do this systematically.

Here you are: https://file.re/2021/05/06/discreet-launcherv330/
Don't forget to use the export/import feature to retrieve your settings when switching from one version to the other.

> -need swipe sometimes ?

=> Probably not most of the time, it will depends on your number of favorites and screen orientation.

> -others apps may can override the priority on the bar ?
-after many notifications, can it be difficult to find list ?

=> This is a sticky notification so it should be displayed first in the list most of the time, if you have other sticky notifications with higher priority it can be a bit lower.

> -transparent bar ?

=> Transparent status bar is already available as a setting since v1.3.0 (ticket #5).

> after the favorites follow users, would there be a need to keep the old favorite homescreen?

=> Navigation can indeed be done using only the new notification-favorites and the drawer.
However, the favorites panel on the home screen will always stay as it is one of the core features of the application (even with the new notification, I still use it a lot because this is what I am used to).

> float can be high efficent many scenarios, 1click shows in any situation.

=> Yes probably, but as explained in my previous comment I will not be able to implement it (require protected permissions which are granted only to system, phone vendors and some huge companies like Facebook).

**Comment by xi7** [comment] 2021-05-06 20:16
https://user-images.githubusercontent.com/67331785/117359886-6d767180-ae8e-11eb-8ee2-9283b1162d2d.mp4

i cant use without auto back to home screen, it working appropriately ? android 5.0

**Comment by xi7** [comment] 2021-05-06 22:37
https://user-images.githubusercontent.com/67331785/117373767-46299f80-aea2-11eb-8dfe-33585555c7e0.mp4

another problem... bug drawer and app freeze

**Comment by xi7** [comment] 2021-05-06 23:11
maybe u need add close button also make the fallow_view independent to the point of making gridview and homescreen unnecessary

**Comment by xi7** [comment] 2021-05-07 12:50
![Screenshot_2021-05-07-09-37-27](https://user-images.githubusercontent.com/67331785/117452001-a3ad0300-af19-11eb-9986-7c7771a3fcea.png)
**quantity into the house**

**Comment by xi7** [comment] 2021-05-08 09:36
the gridview will only be useful when new apps have been installed, i will use everything in the favorites as shown last pic (all_apps), much more interesting the access by the notifications, fast and efficient. but it gets ugly disorganized :(

![Screenshot_2021-05-07-09-37-27](https://user-images.githubusercontent.com/67331785/117534392-977f7f00-afc7-11eb-95e9-ec3b54011d65.png)

1 or 2 ?

**Comment by falzonv** [comment] 2021-05-08 09:44
Indeed, screenshot 1 looks better :-)

The folders will be first in the favorites in the future release v3.4.0.
For the text added in the icon, it may take a bit more time.

**Comment by xi7** [comment] 2021-05-08 09:56
link temporary upload 3.4.0 when possible. tnks

**Comment by xi7** [comment] 2021-05-10 16:08
two problem pesistent layout when open favorites bar

1 = no show all list item
2 = click out layout but open app


https://user-images.githubusercontent.com/67331785/117690005-baa95a80-b190-11eb-88a0-6d25c4b6868a.mp4

**Comment by falzonv** [comment] 2021-05-12 17:05
Since v3.3.0 is finally available on F-Droid, I will close this ticket.
Discussion about bugs #39 and #43 should continue in their respective tickets.

**Closed by falzonv** 2021-05-12 17:05 UTC
Labels: feature/improvement request, solved
