### ISSUE TITLE
Background image coverage in widescreen view

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#132] opened 2021-09-22 01:46 UTC
![bilde](https://user-images.githubusercontent.com/13802408/134270302-db60051b-b823-4f9f-8ef9-89b8d89a5fce.png)

The left part is never covered.
Curiously the right part is covered for "all apps".

**Comment by falzonv** [comment] 2021-09-22 18:17
This seems to be a glitch related to the notch (only way I can reproduce it), even the status bar has a left margin...
I think I have found a fix, it should be solved it in the next release ;-)

> Curiously the right part is covered for "all apps".

=> Yes, since the "all apps" view takes all the screen, the navigation bar is colored accordingly.
I didn't do it for the favorites view because it would look strange on the bottom right corner (the navigation bar cannot be partially color, it is either all the bar or nothing).

**Comment by falzonv** [comment] 2021-10-04 16:09
Since v5.1.0 is now available on F-Droid, I will close this ticket.
Feel free to add comments if needed or wished.

**Closed by falzonv** 2021-10-04 16:09 UTC
Labels: bug, solved
