### ISSUE TITLE
No icon packs found

### ISSUE THREAD

**Issue by Pepper56** [falzonv/discreet-launcher#15] opened 2021-03-22 02:51 UTC
There is an option to change icons in the settings. But the launcher does not detect icon packs on my phone?

**Comment by falzonv** [comment] 2021-03-22 17:44
Hello,

Which icon packs have you installed on your phone?
(by default there are no icon packs, it should be installed from an applications store)

Normally it should work with most icons packs as long as they follow the format given in [this guide to create icon packs](https://forum.xda-developers.com/t/guide-how-to-create-icon-packs-for-go-nova-apex-holo-adw-launcherpro-xperiahome.2399426/) which seems to be a standard as it covers all the major launchers.
At least, I can confirm that it works fine with "Arcticons", "Ameixa Monochrome" and "MBE Style" (icon packs on F-Droid that I tested) and also has been confirmed that "Articons" works in ticket #2.

If a pack is not working and its source code is available, I could try to see what is going wrong and how to fix it.

Best regards.

**Comment by falzonv** [comment] 2021-04-16 09:18
Hello,

When reading again your message, I realize that maybe you did not installed any icon packs on your phone.
In this case, this is normal that Discreet Launcher cannot find any...

I will close this ticket but feel free to add comments if needed.

Best regards.

**Closed by falzonv** 2021-04-16 09:18 UTC
Labels: invalid / not reproductible, missing information
