### ISSUE TITLE
Back button when navigating in the settings

### ISSUE THREAD

**Issue by RichFrogg** [falzonv/discreet-launcher#159] opened 2021-11-30 19:27 UTC
Would it be possible for the back button to get back to the main Discreet Launcher menu instead of closing the the app and having to go back and relaunch it.

Thanks!

**Comment by falzonv** [comment] 2021-12-06 16:28
Hello,

Thank you for the report!
Could you add a bit more detail of when you observe this behavior with the Back button?

It was the very first bug I solved (#1) so I would be really surprised it appeared again out of nowhere after 9 months :joy:

The expected behavior of the back button is as follow:
- When something (favorites panel, launcher menu, folder, app drawer) is opened: close it
- When on the home screen with nothing opened: do nothing

Normally the launcher itself should never be closed as this is the starting point for launcher other apps.

Best regards.

**Comment by RichFrogg** [comment] 2021-12-06 17:05
Hey Vincent, thanks for getting back to me. It's not really a big issue after I realized I could launch the menu with the pull down menu but I took a screen recording of what is happening. I'm using a Samsung S21 Ultra.

Thanks!

Rich
________________________________

**Comment by falzonv** [comment] 2021-12-09 09:55
Hello,

It seems GitHub doesn't handle attachments by mail because I cannot see the screen recording.

Nevertheless, I understand the request now :-)
When you said "closing the app", I thought you were brought back to the Android stock launcher which looked impossible except in the case of an app crash.

About the Back button behavior when navigating in the settings, I agree this is not ideal that the menu is closed each time.

When implementing the new menu this summer, I tried to make the Back button go back to the main menu (like it is for Changelog/Help/About small dialogs) but it caused several even more confusing bugs.
For example, you would change the favorites but when pressing Back and going back to the main menu, the old favorites panel would still be displayed in background of the menu dialog (and the same for most appearance settings). Or when pressing the Home button (from which the behavior cannot be overridden), you would come back to the home screen but the menu would still be displayed until you dismiss it with Back or clicking outside of it. There were other bugs but I mainly remember those...
After having tried many ways which added a lot of code complexity and potential maintenance troubles, I decided to stay with the current behavior which solved all the bugs I had noticed.

I will close the ticket as I already spent many evenings this summer trying other ways without coming to a better compromise.
Well, at least now you know why it is like so...

Best regards.

**Closed by falzonv** 2021-12-09 09:55 UTC
Labels: feature/improvement request, won't do/fix (see closure comment)
