### ISSUE TITLE
Feature idea - Adjustable menu, folder and search background colours

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#196] opened 2022-03-11 05:22 UTC
Loving the new 6.1.0.
Found out I can remove the menu button and just have the Discreet app in favourites.

The gray colour of the menu is a bit drab.
I think a more floating feel can be had with a transparent background (maybe by default)?

The search should ideally use the colour from the app drawer so that it looks familiar.
Ideally it would search right in the app drawer view, instead of a new layer on top of it.

There is also a colour for folders.

**Comment by falzonv** [comment] 2022-03-11 15:20
Hello,

Thank you for the suggestions!

> The gray colour of the menu is a bit drab.
> I think a more floating feel can be had with a transparent background (maybe by default)?

=> You mean the Discreet Launcher menu ("Favorites", "Folders", "Hidden apps", etc.) when using dark theme?
For this part I simply let the Android system manages the text and background colors for the menu (only telling the system to use a light or dark theme), maybe because the menu is a dialog the system makes it lighter than a window background.

> The search should ideally use the colour from the app drawer so that it looks familiar.
> [...]
> There is also a colour for folders.

=> Interesting idea, we could indeed reuse the user-defined app drawer background color for Search background, and probably also for folders backgrounds (that way everything looks consistent). I will have a look...

Since the color for folders is intended for the icon, I do not think it would look good as a background. But this color could be used for folder borders (at the same time I am also thinking of a possible redesign of folders, with rounded corners, no outside borders and just a line separating the title from app names ; this line could be the same color as the icon).

> Ideally it would search right in the app drawer view, instead of a new layer on top of it.

=> Perhaps, but it is not really possible without regression at this stage because the Search can be added to favorites, meaning that it can be called from the favorite popup and displayed over other apps. Display the app drawer view at this time would require to go back to the home screen (as this view is part of the home screen) which is not desired. (And I do not plan to implement two different searchs as the current one is already able to handle both cases in an acceptable way.)

Best regards.

**Comment by falzonv** [comment] 2022-03-26 23:11
Hello,

As mentioned in ticket #197, when the next release will be published (not ready yet), the following will be changed:

>   - The folder title and the separating line will be the same color as the folder icon
>   - The folder background will be based on app drawer background color, with a transparency like in screenshot 1 above to make sure app icons and names always stay visible
>   - The app names will be the same color as the text color selected for the app drawer

Best regards.

**Comment by falzonv** [comment] 2022-03-30 16:59
Hello,

What was described in the last comment was implemented in new release v6.2.0!
I will leave this ticket open until it is available on F-Droid (usually takes 4 to 8 days).

Best regards.

**Comment by falzonv** [comment] 2022-04-02 11:33
Since yesterday v6.2.0 is available on F-Droid so I will close this ticket.

**Closed by falzonv** 2022-04-02 11:33 UTC
Labels: feature/improvement request, solved
