### ISSUE TITLE
Access to favorites active even when DL not set as launcher

### ISSUE THREAD

**Issue by AeOeAa** [falzonv/discreet-launcher#45] opened 2021-05-12 20:09 UTC
By chance I've discovered that with Discreet Launcher (DL) installed and native launcher active, the "Access to favorites" notification is still present.

At first DL was set as default launcher, and the access to favorites turned on. Then a crash (not because of DL) reset the launcher in Settings, and the access to favorites still visible in notifications. I can reproduce by setting DL as launcher, then setting native launcher

v3.4.0 from APK on Android 10

**Comment by falzonv** [comment] 2021-05-12 20:53
Hello,

Thank you for the bug report, I was also able to reproduce it.
Unfortunately, I am not sure if this one can be solved :-/

The behavior of the notification is to appear when something else than the home screen of Discreet Launcher is displayed (that is, another application being used). It is also sticky in order to be high in the list and not dismissed by mistake (if it was dismissed, the user would need to come back to Discreet Launcher and reopen an application to have the notification back).
When the user comes back on the home screen (and only at this moment), the notification is hidden.

If changing the default launcher, it seems that Android does not "kill" the former launcher so it stays active in background. This is most probably the reason why the notification is still displayed even if Discreet Launcher is not the default launcher (you can easily check this by "force stopping" it in the app settings, the notification will disappear).

The problem is that we cannot display or not the notification depending on the current default launcher because at the moment the notification is displayed (leaving the home screen to open something else), Discreet Launcher will still be the default launcher so the check would always say "true" and the notification would always be displayed. And once the notification is displayed, it is not possible to hide it without coming back to the home screen.

I will let the ticket opened for 1 or 2 days in case I have an idea, but I am afraid we will have to close it without fix...

Best regards.

**Comment by AeOeAa** [comment] 2021-05-13 07:13
I think that makes sense and it is an edge case (changing launchers) so
don't think any more has to be done about it, just wanted to document it,
also in case something else comes up that might be related to this "super
sticky notification" thingy 😊

**Comment by falzonv** [comment] 2021-05-13 07:38
Hello,

Yes you are right, I will close this ticket.
Thank you for the report, and it may indeed be useful to link to this ticket in the future :-)

Since an help section about notification was created in v3.5.0 for #39, I still added a line about this bug and a workaround (reopen Discreet Launcher—no need to be default launcher—and disable the notification in the settings).

Best regards.

**Closed by falzonv** 2021-05-13 07:38 UTC
Labels: bug, won't do (see closure comment)
