### ISSUE TITLE
IconPackStudio Support

### ISSUE THREAD

**Issue by n-ce** [falzonv/discreet-launcher#203] opened 2022-04-06 04:03 UTC
Whenever I try to apply icon packs from the icon pack studio app, it says this
![Screenshot_20220406-092921](https://user-images.githubusercontent.com/69345507/161893246-c8c28b0a-cce7-449e-b634-426dab0bcdb8.jpg)

**Comment by falzonv** [comment] 2022-04-06 18:24
Hello,

Thank you for the report!

After further investigation, it seems that IconPackStudio stores the `appfilter.xml` file in `res/raw/appfilter.xml` while Discreet Launcher searches this file in the location `res/xml/appfilter.xml` which is the default location.
https://docs.smartlauncher.net/other-products/iconpackstudiofaq/faq-for-launcher-developers

This explains why even the stock Android launcher is not compatible with IconPackStudio, it should probably also search only at the default location and not check the raw files.
https://docs.smartlauncher.net/other-products/iconpackstudiofaq/supported-launcher

Not sure if many other icon packs store the file in "raw" instead of "xml"...
I guess the easiest solution will be to search the XML file at both locations and take what works, I will have a look.

Best regards.

**Comment by falzonv** [comment] 2022-05-19 16:24
Hello,

I am pleased to inform you that this should be solved in new release v6.3.0!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

Let me know if it still doesn't work, we will have to investigate further...

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by saraid2** [comment] 2023-02-18 00:16
When I try to apply the theme the application stops working and I can only open it again if I delete the data in the settings.

**Comment by falzonv** [comment] 2023-02-23 16:25
Hello @saraid2,

Thank you for the report!

Could you send me (as an attached file in GitHub) an example of icon pack generated with IconPackStudio so that I could try to reproduce the issue on my side?

Best regards.

**Comment by n-ce** [comment] 2023-02-23 17:38
**Off-Topic** : *Forgive me Vincent, that I never came back to mention the consecutive issues of this implementation to you because I simply moved on from discreet after some time...*

**Comment by falzonv** [comment] 2023-03-17 16:16
Hello @n-ce,

No worries :-)
As you can see from my late answer, I am much less reactive on this personal project than before (saw your message only now) because of the workload in my job and this is why I preferred to notify people about it.

Just noticed something funny though: initially you moved away from Discreet Launcher for (I guess) better support, but the last release from Ultra was 10 months ago (on 29th May 2022, two weeks after I posted the maintenance status) while the last release from Discreet Launcher was last month!
(Not a critic, I use much older apps everyday on my phone, I just find the coincidence funny)

Glad you found a launcher that you are satisfied with, I was never really happy with the launchers I tried and this is part of why I coded my own (another reason was to discover Android programming, and another to get rid of the Google search bar).

Best regards.

**Comment by falzonv** [comment] 2023-08-04 17:42
Let's close it again, it has been 5 months since the initial exchange and no more info was provided

**Closed by falzonv** 2023-08-04 17:42 UTC
Labels: feature request, missing information, won't do/fix (see closure comment)
