### ISSUE TITLE
Customize clock

### ISSUE THREAD

**Issue by jcperil** [falzonv/discreet-launcher#213] opened 2022-04-29 23:50 UTC
**Description:**
Currently, the format and font size of date & time looks very big. And the positions top, middle, bottom are a little limited in the sense that some of my favorite wallpapers look bad.

**Feature Request:**
Allow customization of

1. Date format: In my opinion, Sat, 30 Apr (shortened and without the year) looks better than Saturday, 30 April, 2022. It saves room for the wallpaper to shine. It would be nice to have options.

2. Font size: You made it clear in #103 that font settings isn't feasible. Can settings for font size be implemented? It enhances the wallpaper a lot as illustrated below. 

3. Clock position: Allow more positions like top right, top centre, top left etc.

**Additional comments:**
Before you dismiss this issue, please take a look at some wallpapers of what it looks like vs what it could have been.

<img width="40%" src="https://user-images.githubusercontent.com/89805719/166081405-762c5eac-2e8c-4ec5-b0b5-31a553389e45.png"/> <img width="40%" src="https://user-images.githubusercontent.com/89805719/166081396-2e8a3080-dc42-49ae-98ae-85b48053a106.png"/>

<img width="40%" src="https://user-images.githubusercontent.com/89805719/166081422-d4046ea6-76a8-4b6c-94d9-c12144e04b42.png"/> <img width="40%" src="https://user-images.githubusercontent.com/89805719/166081412-05df1dfe-3876-4b99-b036-cc35872574fc.png"/>

<img width="40%" src="https://user-images.githubusercontent.com/89805719/166081436-999326f6-bb0e-4599-ae3c-6a9b52bea404.png"/> <img width="40%" src="https://user-images.githubusercontent.com/89805719/166081427-33ce2429-8aeb-48bb-bbcc-0848777c5513.png"/>

<img width="40%" src="https://user-images.githubusercontent.com/89805719/166081450-1ac67747-b9b2-448f-b865-e143315b5229.png"/> <img width="40%" src="https://user-images.githubusercontent.com/89805719/166081441-fb8129dc-2c8b-40aa-9c48-c64fabfde80c.png"/>

*Edit from Vincent: screenshots down-sized for better readability*

**Comment by falzonv** [comment] 2022-05-04 16:58
Hello,

Thank you for the suggestions!
I will have a look to see what can be done ;-)

Just so that you are not surprised, I should mention that it will probably take a long time as I am currently very busy with my job.

---

> Date format: In my opinion, Sat, 30 Apr (shortened and without the year) looks better than Saturday, 30 April, 2022. It saves room for the wallpaper to shine. It would be nice to have options.

=> Actually the full date format is defined by Android based on the system language. It means that a French or Spanish user would get a different output than an English user (all of this is managed automatically by Android).
For example, in French I have "samedi 30 avril 2022" while in English I get "Saturday, 30 April, 2022" as in your example.

Maybe Android can do the same thing with a shorter date format, I have to check...

Best regards.

**Comment by jcperil** [comment] 2022-05-14 12:09
> Actually the full date format is defined by Android based on the system language.

I would like to add that the pictures in the second column (with shorter date format feature) are screenshots from [Olauncher](https://github.com/tanujnotes/Olauncher).

**Comment by falzonv** [comment] 2022-06-28 16:52
Hello,

Just to keep you informed, I am making good progress on this ticket :-)

The following should be part of the next release (probably somewhere in July):
- 9 clock positions (any combination of top/middle/bottom with left/center/right) instead of the current 3
- Option for the shorter date format, I was able to find it.

Still working on the custom clock size which is more complex than I though, we will see...

Best regards.

**Comment by jcperil** [comment] 2022-06-29 18:58
Thank you.

> Still working on the custom clock size which is more complex than I though, we will see...

I think I understand why. Since it will most likely not be implemented, can you make the font of date & time smaller like the pictures in the right column?

**Comment by falzonv** [comment] 2022-07-12 16:18
Hello,

*(My reply is a bit late, I was away and without Internet access last week.)*

> can you make the font of date & time smaller like the pictures in the right column?

Yes perhaps, another idea that I had during my holidays (no time to test it yet, maybe this week-end) would allow to provide a font size setting with 3 values such as:
- Small => similar to your screenshots
- Medium => the current size
- Large => although Discreet Launcher was designed for phones, some users have it on tablet so this may be useful

Best regards.

**Comment by jcperil** [comment] 2022-07-16 16:10
If it can be implemented, why not! It is definitely better.

**Comment by falzonv** [comment] 2022-07-26 15:20
Hello,

I am pleased to inform you that this has been implemented in new release v6.4.0!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment] 2022-08-12 20:41
Since end of July v6.4.0 is available on F-Droid so I will close this ticket.

**Closed by falzonv** 2022-08-12 20:41 UTC
Labels: feature/improvement request, solved
