### ISSUE TITLE
 folders

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#22] opened 2021-04-09 18:23 UTC
possibility to create folder on the home screen

-games
-tools
-cameras/editors

**Comment by falzonv** [comment] 2021-04-10 19:22
Hello,

Thank you for your suggestion!

Ok to try to add folders in the applications drawer, but not on the home screen itself (the goal of the launcher is to provide an empty and clean home screen).
Please note that it will probably take some time (many things to change and test), I will keep you updated.

Best regards.

**Comment by xi7** [comment] 2021-04-10 22:39
precisely to keep the home screen cleaner and better organized.

example, a gamer folder can contain a lot games applications since the launcher does not yet offer the ability to search.

-you could also decrease the amount of margins and padding for a better use on the screen. gridview/home

**Comment by falzonv** [comment] 2021-04-11 09:37
Hello,

Yes, perhaps in the favorites panel but not directly on the home screen.
Maybe the best would be to manage folders in the drawer, and then folders could be selected as favorites if the user wants.

> you could also decrease the amount of margins and padding for a better use on the screen. gridview/home

In fact currently it is set to 4 columns and the margins/padding are adapting automatically. Maybe in the future I will try to adapt the number of columns to the screen width (but there are already many things to do before).

Best regards.

**Comment by falzonv** [comment] 2021-04-19 17:31
Hello @xi7, @Thewisem,

This message is just to let you know that I am progressing quite well on folders.

If we look at it as 3 big steps, the current status would be:
1. Folders integration (display correctly in the list, open/close, show apps, add in favorites, ...) => **DONE**
2. Interface to manage folders (new, remove, rename, add/remove apps, ...) => TO DO
3. Many tests and probably corrections => TO DO

Best regards.

**Comment by xi7** [comment] 2021-04-20 11:37
folders can be just a shortcut with names.
-example: (after click shortcut folder games, list on gridview what was chosen)

a ideia era apenas diminuir a quantidade de icones na tela principal, but not problem add full folders method.

**Comment by falzonv** [comment] 2021-04-27 10:46
Hello,

I am pleased to inform you that folders have been implemented in release v3.1.0!
This release was finalized on 23rd April and, after the usual publishing delay, it is now available since today on both F-Droid website and Android client.

Since this is now implemented I will close this ticket, feel free to add comments if needed or wished :-)

Best regards.

**Closed by falzonv** 2021-04-27 10:46 UTC
Labels: feature/improvement request, solved

**Comment by AeOeAa** [comment] 2021-04-28 04:53
Hello

Long time no hear 😂 but I'm still here, following all the changes and improvements, excitedly waiting for the new versions to show on the F-Droid.

So, I have been using folders for a couple of days, since this version came to F-Droid. I love that you made folders, thanks both to you and to xi7 for the idea!

First impression is that there are some things that it took some trialling to figure out. Would it be possible to have the same app in different folders (no). Would it be possible to have in favourites both a folder with AppX in it and AppX (yes). Maybe write it in the help section?

The uniform folder icons do look sleek in favourites 😀

I would like to have some way of making the folder icons distinguishable. My workaround is using smileys in the beginning of the folder label as metaphors for the subject of the folders: 📰📱🎮🎶📽️💵🕹️🔒📳📚⚕️📧📣

To round up my initial take away, there's some odd behaviour when renaming a folder. At some point, it led to a folder already added as favourite no longer being in favourites, having to add it again. I don't know if I can recreate, but I'll get back to you if I get any wiser on what happens.

But the bottom line is it works, and it's also a way for app hoarders to have many favourites.

When I find the time, I'll get back to you on some of the older changes that I'm very happy about but never got around to reply on.

Best wishes!

**Comment by Thewisem** [comment] 2021-04-28 04:58
Has anybody thought about tab implementations? Like in the nova launcher. During this development. Or was it just me?

**Comment by xi7** [comment] 2021-04-28 10:56
excellent folder!

just a better organization list folders first a-z

**Comment by falzonv** [comment] 2021-04-29 08:47
Hello,

---

Thank you very much @AeOeAa for this detailed feedback, I am glad that you like the new folders option!

> First impression is that there are some things that it took some trialling to figure out. Would it be possible to have the same app in different folders (no). Would it be possible to have in favourites both a folder with AppX in it and AppX (yes). Maybe write it in the help section?

=> Good idea, I will add explanations to clarify this in the Help section (created ticket #34 for follow-up).
Not sure if many people would read them but at least it would exist somewhere in the application.

> The uniform folder icons do look sleek in favourites :grinning:
I would like to have some way of making the folder icons distinguishable. My workaround is using smileys in the beginning of the folder label as metaphors for the subject of the folders: :newspaper: :iphone: :video_game: :notes: :film_projector: :dollar: :joystick: :lock: :vibration_mode: :books: :medical_symbol: :e-mail: :mega:

=> You are right, it would be good to allow for custom icons. The problem is that the proposed icons must come from somewhere (the uniform folders icon is embedded with the launcher). It could be taken from the installed applications icons but it may create confusion if the same icon is used both for an application and a folder.

I find your workaround awesome!
=> Now I wonder if this can be an idea for the folder icon selection: the user would choose any of the smileys on his/her phone, and this smiley would be converted in a folder icon (no idea yet if this is possible, it may look completely blurry if we only have access to the small version of the smiley).

=> Created ticket #35 for follow-up and tests about this.

> To round up my initial take away, there's some odd behaviour when renaming a folder. At some point, it led to a folder already added as favourite no longer being in favourites, having to add it again. I don't know if I can recreate, but I'll get back to you if I get any wiser on what happens.

=> It is indeed a bug, thank you for the report (created ticket #33 for follow-up).
Even found an idea of the reason: currently, when a folder is renamed, the favorites internal file is not updated with the new name (since the old name refers to a folder not found anymore, it is not displayed).
=> It is something I had missed... will be corrected in a future release (meanwhile, the only way is indeed to add it again).

---

> @Thewisem: Has anybody thought about tab implementations? Like in the nova launcher. During this development. Or was it just me?

=> The only discussion about tabs was in our exchange from #27 (for information, I am a single developer so there are no team meetings during the development).
As mentioned in ticket #27, I will not implement both tabs and folders because the purpose is very similar. Looking at feedback above about folders, it seems to be a much more flexible option (as it can also be added in favorites panel) so I will stay with folders.

---

Thank you @xi7 for your feedback, I am very happy that you like the new folders option!

> just a better organization list folders first a-z

=> Good idea, I agree that it would look better (created ticket #32 for follow-up).

---

*Note: being quite busy currently, I will probably not start to work on the new tickets before next week*

Best regards.

**Comment by ycbmwig3338** [comment] 2021-04-30 13:14
Hello looks good so far. Despite being an older geek i am not familiar with Github. My discord server Weird Studies has a similar tab like use of emojis maybe search for it and check it out?

**Comment by falzonv** [comment] 2021-05-04 16:36
Hello,

Thank you for your suggestion, I do not use Discord but feel free to share a screenshot if you want ;-)
*(instructions to attach a file to a GitHub comment are between the writing area and the "Comment" button)*

Best regards.
