### ISSUE TITLE
v3.6.0 crashes on Android 5

### ISSUE THREAD

**Issue by KaiFujiro** [falzonv/discreet-launcher#55] opened 2021-05-20 01:32 UTC
I finished installing update v3.6.0, but it crashed when I wanted to move from the default launcher to the discrett launcher

*Android 5.1.1

**Comment by falzonv** [comment] 2021-05-20 21:34
Hello,

Thank you for the bug report, for now I was not able to reproduce the issue (that is, I do not observe any crash).

Did the issue happened after switching from the F-Droid version to the APK version?
If yes, do you observe the same issue with using the APK of v3.5.0?

Will continue to try to reproduce the issue...

Best regards.

**Comment by KaiFujiro** [comment] 2021-05-21 18:10
I'm using the github version

**Comment by KaiFujiro** [comment] 2021-05-21 18:11
I didn't find any crashes in version 3.5.0

**Comment by falzonv** [comment] 2021-05-22 16:18
Ok, thank you for the details.
This is quite strange because there were not much changes in the way the launcher starts between v3.5.0 and v3.6.0 (and those changes were only for Android 10+).

When it is available on F-Droid (probably tomorrow) I will make additional tests on an emulator with Android 5 but for now still no idea of the reason unfortunately :-/

**Comment by xi7** [comment] 2021-05-23 10:59
this happen only when is not the default launcher and click the favorites bar.

**Comment by falzonv** [comment] 2021-05-23 17:47
Today I tried with the F-Droid version and Android 5 to see if it was different but I still do not see any crash :-/
(tried with direct install of v3.6.0, and also with install v3.5.0 followed by upgrade to v3.6.0)

Also tried what you suggested @xi7 (click the notification when not default launcher), but it opened the notification without crash...

Well, no crash are good news but that will not help to solve this issue...
Many things will be changed internally in the next release due to several new features complex to implement (in progress), maybe it will solve the crash or make it easier to reproduce.

Waiting for this, it seems you will have to stay with v3.5.0, sorry :-/
(Or maybe try another install, **xi7** is also using Android 5 and was able to upgrade to v3.6.0)

**Comment by falzonv** [comment] 2021-06-05 16:58
Hello @KaiFujiro,

For information a new version v4.0.0 has been published few minutes ago.

It doesn't explicitly solves this bug, since I was never able to reproduce it in the first place.
However, there were many internal changes with this new version so maybe this issue is solved at the same time.

Could you please try and tell me if you still observe the bug?

Best regards.

**Comment by falzonv** [comment] 2021-06-19 07:09
Hello @KaiFujiro,

New release v4.1.0 is published.
If you are still using the launcher, does this new release works for you?

Please note that if no answer and after v4.1.0 is effectively published on F-Droid, I will close this ticket as "not reproductible".

Best regards.

**Comment by KaiFujiro** [comment] 2021-06-21 11:32
I tried github version 4.1.0 but when it crashes, but when I try version 4.1.0 F-droid doesn't crash

**Comment by falzonv** [comment] 2021-06-22 05:14
Hello,

Ok thank you for your feedback, good news if the F-Droid version is working for you!

It is quite strange that you still see a crash with the GitHub version :-/
Unfortunately, I am not able to reproduce this crash to search what could go wrong (and, as far as I know, **xi7** didn't encountered any crash either with the GitHub version using Android 5).

If someday I have an idea that could solve this crash we will try, but for now I can provide you only the F-Droid version.

Best regards.

**Closed by falzonv** 2021-06-22 05:14 UTC
Labels: bug, invalid / not reproductible
