### ISSUE TITLE
system apps.

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#311] opened 2023-07-27 16:19 UTC
after disable/enable system apps gridview cannot update.

replace added to changed.

**Comment by falzonv** [comment] 2023-08-04 18:04
Hello,

Thank you for the tip, I will have a look.
It will probably need to have both "added" and "changed", otherwise newly installed apps may not be detected anymore.

Best regards.

**Comment by falzonv** [comment] 2023-08-19 09:33
Hello,

This has been implemented and will be part of the next release (probably somewhere in September).

It was a bit trickier than expected because the behavior varies across Android versions: in older versions a newly installed app will only trigger ADDED, but in newer versions it will trigger both ADDED and CHANGED (I made the tests with Android 5 and 11 so the behavior change happens somewhere in between).
So I had to make additional checks to avoid updating the list twice when a new app is installed.

Best regards.

**Comment by falzonv** [comment] 2023-09-05 13:44
Hello,

Following issues reported in #316, I made a rollback of this change in v7.4.1.

I already noticed that the PACKAGE_CHANGED intent was used for more than system apps and has spent a couple of hours trying to make sure it would not cause unnecessary updates before publishing v7.4.0.
However this was apparently not enough and, since I cannot reproduce the update messages described in #316, I guess some specific devices and/or Android versions are using this intent for other purposes, causing unexpected updates.
This is not something I will have the time to investigate and maintain for all possible edge cases so it will not be implemented.

Best regards

**Closed by falzonv** 2023-09-05 13:44 UTC
Labels: won't do/fix (see closure comment), improvement request
