### ISSUE TITLE
Add setting to force portrait mode

### ISSUE THREAD

**Issue by c0bnut** [falzonv/discreet-launcher#23] opened 2021-04-10 05:29 UTC
There is currently no setting to force the home screen into portrait mode. This way you can have auto rotation enabled for apps but not the home screen.

**Comment by falzonv** [comment] 2021-04-10 14:35
Hello,

Thank you very much for your suggestion!
I will probably add this setting in the next release v2.6.0, good idea :-)

Do you think the setting should also force portrait mode in the applications drawer or only the home screen?

Best regards.

**Comment by falzonv** [comment] 2021-04-10 18:01
Hello again,

After some tests, I have answer to my own question:
> Do you think the setting should also force portrait mode in the applications drawer or only the home screen?

=> **Only home screen.**

It works fine with only the home screen but an issue that I am not able to solve appears when adding the applications drawer.

More precisely, here is the scenario where we can observe the issue:
- Starting from the home screen with forced portrait option enabled
- Turning the phone to landscape orientation (display stays in portrait as expected with the option)
- Performing the gesture to open the application drawer
- The issue is during the transition: the drawer appears in landscape for a small moment before pivoting to portrait
  -  During this transition the user interface is not usable, (s)he can only wait that it is finished
  -  I said "transition" but this is not like an animation, in fact Android creates the drawer activity in landscape mode, then destroys it and recreates it in portrait mode (so it is not smooth and cannot be improved)
- After the applications drawer is in portrait mode, the forced mode is working as expected

I have observed this issue with Android 8.1 and Android 11 so it probably happens with all versions in between. The time during which the interface is not usable is between 1-2 seconds and only few milliseconds (depending on device specifications).
Even the few milliseconds delay is not good because it make a sort of blinking/flashing transition with is not good.

Unfortunately I am not able to solve this issue (tried many things but nothing works...) so this setting will be only for the home screen in order to not degrade user experience.

*Note: even in home screen only, there was also an issue with Android 8.1 (not Android 11) when coming back from the settings to home screen and pivoting the device. I was able to solve it but the workaround does not solve the transition issue.*

Best regards.

**Comment by falzonv** [comment] 2021-04-11 09:23
Hello,

Two updates!

**1/ Setting to force portrait mode implemented in v2.6.0** (home screen only for now)

This new release has been pushed to the stores few minutes ago and the usual publishing delay is:
- 0 to 2 days for Google Play
- 4 to 8 days for F-Droid

**2/ Possible solution to apply this setting to both home screen and drawer** (would be better in my opinion)

For the next release, I am thinking about putting both the home screen and the applications drawer in the same Android activity (would require a major internal refactoring, but also remove duplicated code and simplify many things at the end).

If this works fine, it would solve the issue described in my previous message at the same time (no transition anymore because we would stay in the same Android activity when navigating from home screen to drawer).

*Note: even after v2.6.0 is published on both stores, I will keep this ticket opened for follow-up of point 2 above.*

Best regards.

**Comment by c0bnut** [comment] 2021-04-12 06:20
> 
> 
> Hello,
> 
> Two updates!
> 
> **1/ Setting to force portrait mode implemented in v2.6.0** (home screen only for now)
> 
> This new release has been pushed to the stores few minutes ago and the usual publishing delay is:
> 
>     * 0 to 2 days for Google Play
> 
>     * 4 to 8 days for F-Droid
> 
> 
> **2/ Possible solution to apply this setting to both home screen and drawer** (would be better in my opinion)
> 
> For the next release, I am thinking about putting both the home screen and the applications drawer in the same Android activity (would require a major internal refactoring, but also remove duplicated code and simplify many things at the end).
> 
> If this works fine, it would solve the issue described in my previous message at the same time (no transition anymore because we would stay in the same Android activity when navigating from home screen to drawer).
> 
> _Note: even after v2.6.0 is published on both stores, I will keep this ticket opened for follow-up of point 2 above._
> 
> Best regards.

Thank you for your fast responses.

**Comment by falzonv** [comment] 2021-04-16 09:10
Hello,

I am pleased to inform you that the issue with the applications drawer has been fixed in release v3.0.0!

This new release v3.0.0 has been pushed to the stores few minutes ago and the usual publishing delay is:

- 0 to 2 days for Google Play
- 4 to 8 days for F-Droid

*Note: I will leave this ticket opened until the release is effectively published on both stores.*

Best regards.

**Comment by falzonv** [comment] 2021-04-21 17:05
Hello,

This release being now available on F-Droid, I will close this ticket.
Feel free to add comments if needed :-)

Best regards.

**Closed by falzonv** 2021-04-21 17:05 UTC
Labels: feature/improvement request, solved
