### ISSUE TITLE
some app never hide

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#71] opened 2021-06-19 23:08 UTC
https://user-images.githubusercontent.com/67331785/122657429-e2012900-d139-11eb-836a-f26e403affef.mp4

test show simple keyboard never hide

**Comment by xi7** [comment] 2021-06-20 10:48
this happens when import old file txt to new 4.1.1.

after start new config working normally

**Comment by falzonv** [comment] 2021-06-22 04:42
Ok, thank you for the bug report.
For now I was not able to reproduce it, the conversion from old to new format (as per ticket #66) seems to work well in most cases.
Could you please share the lines from the import file which starts with ``hidden.txt:``?

**Comment by xi7** [comment] 2021-06-22 14:25
deleted the old file txt. but the problem is when import old version file.

**Comment by xi7** [comment] 2021-06-22 14:31
dark mode no work if import old file even if enable and disable, need clear app data and make new config

**Comment by falzonv** [comment] 2021-06-22 17:03
Strange, I didn't had issues when testing the import with older files having hidden applications.

I have an idea to make the conversion more reliable, will try in the next release ;-)

**Comment by falzonv** [comment] 2021-06-26 08:55
Hello,

I am pleased to inform you that this should be solved in new release v4.2.0!
This release has been published a few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by xi7** [comment] 2021-06-27 10:34
https://user-images.githubusercontent.com/67331785/123541241-dbfedf80-d719-11eb-9d7c-041e83e28585.mp4

still no work, v.4.2.0

**Comment by xi7** [comment] 2021-06-27 10:44
something wrong happens, now 4.1.1 to 4.2.0, work only while no import txt

**Comment by falzonv** [comment] 2021-06-27 11:34
Ok, thank you for the report.
I am now able to reproduce the issue but it is a bit strange: for me it happens only with applications located in folders, applications not in folders can be hidden normally.

On your video I do not see folders so it may be a different issue, I will try to solve the issue for hiding applications which are in folders and maybe it will solve both at the same time...

**Comment by falzonv** [comment] 2021-07-04 09:47
Hello,

I am pleased to inform you that this should now be (finally) solved in new release v4.3.0!
This release has been published a few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by xi7** [comment] 2021-07-04 18:27
perfect, but strange ghosts when open import file list, show deleted old files.  maybe android 5 only.

**Comment by falzonv** [comment] 2021-07-06 13:38
> strange ghosts when open import file list, show deleted old files. maybe android 5 only.

=> Yes probably, the selection of the import file is fully managed by Android.
I only ask the dialog to be displayed, and receive the name of the selected file after the user validated (same for export).
This allows to not need read/write permissions because everything stays managed by the system (it grants a special temporary read or write permission for the single file selected by the user, not even both permissions at the same time so quite secure).

> clock never save here

=> What do you mean?
If you change the clock in the settings it doesn't work, or the clock settings from an import file are not loaded?
(would be interested to see the settings section of the import file if this is the second case)

**Comment by xi7** [comment] 2021-07-06 18:13
clock settings from an import file are not loaded and some bug if not kill app.


https://user-images.githubusercontent.com/67331785/124647558-7e326c00-de6c-11eb-815d-1b4bc86eb7a0.mp4

**Comment by falzonv** [comment] 2021-07-09 16:44
Ok thank you for the report!
It was not easy to solve but normally it should be ok in new release v4.4.0 published few minutes ago.

Since the bug from this ticket (hidden apps) has been solved, I have created #86 to record these import bugs (so that F-Droid users are informed while v4.4.0 is in publishing process).

v4.3.0 solving the hidden apps issue is published on F-Droid since today so I will close this ticket.

**Closed by falzonv** 2021-07-09 16:44 UTC
Labels: bug, solved
