### ISSUE TITLE
Time is not perfectly centered

### ISSUE THREAD

**Issue by antodc** [falzonv/discreet-launcher#328] opened 2024-05-05 17:50 UTC
When the clock is activated, the time is shown slightly on the right, while I would expect it to be perfectly centered in the screen. The issue is more evident when the (short) date is added, as it is (slightly) misaligned with respect to the time. My impression is that the date is fine, but the time is not. My settings are in Italian, but the issue is still there if I use English. Same issue also on my wife's phone.

**Comment by falzonv** [comment] 2024-05-18 20:58
Hello,

Thank you for the report, I am surprised to never have noticed it before!
Although to be fair, I only use the clock while developing or testing, not in my daily use of the launcher...

The last significant change to the clock was a bit more than one year ago, when adding new clock formats.
I am pretty sure everything was fine before so probably a mistake with horizontal placement was introduced at that time, I will have a look.

Best regards

**Comment by falzonv** [comment] 2024-08-24 10:38
Hello,

For info I also tried to fix this but haven't found yet what causes the issue.
The date is properly centered but the time is not, even thought it seems to use the same formulas for horizontal position, very weird...
I continue to investigate but it may take more time than I expected to fix.

Best regards

**Comment by antodc** [comment] 2024-08-24 11:06
Thanks a lot for your feedback and your efforts!! Could it be an internal issue with the specific clock that is used? Maybe it has a small bug that makes it asymmetric around the colon.

**Comment by falzonv** [comment] 2024-09-04 03:53
Hello,

Thank you for the idea!
Internally both time and date are inserted as simple texts, the respective widths of these texts are computed using Android's method [getTextBounds()](https://developer.android.com/reference/android/graphics/Paint#getTextBounds(java.lang.String,%20int,%20int,%20android.graphics.Rect)) and then used for the formulas.
Maybe this method doesn't handle the measurement of the colon (or any non-alphanumeric character) properly...
If this is the case, I guess a workaround could be to temporarily replace ":" with "i" during measurement.

I will check that when I have some time :-)

Best regards

**Comment by antodc** [comment] 2024-09-04 04:59
I see your point, but there should be something else. I noticed that sometimes the clock moves slightly when the time changes. For instance, it goes to the right from 06:40 to 06:41. So, that function considers a “0” larger than a “1”. Maybe you should compute the difference between the bounds of 00:00 (which should be symmetric around the colon) and those of the real time and use that difference to adjust the position of the clock.
No idea whether this is really of any help, but thanks a lot for your attention.

**Comment by kaanelloed** [comment] 2024-09-11 13:55
Even the date is slightly off-center. The problem is that Paint.getTextBounds() gets the exact bounds of the text, whereas canvas.drawText() adds a space at the beginning and end. When the width is obtained with Rect.width(), the space at the beginning is ignored; the drawn text is therefore larger than the calculated bounds.. See this [comment](https://stackoverflow.com/a/57288746) for an example.

We can fix this in three ways.

**First way**
Remove the Rect.left when drawing the text. Text should be perfectly centered.

```java
canvas.drawText(time_text, offset_x - rect_time.left, offset_y, textClock) ;
```

**Second way**
Get the width with Paint.measureText(). Text can still be slightly off-center if the space at the beginning is different from the space at the end.

```java
float time_width = textClock.measureText(time_text) ;
```

**Third way**
For information purposes only, we're essentially doing the first option, but with a path. We retrieve the path from the text, calculate the path bounds and draw the path instead of the text.

```java
//rect_time is now a RectF instead of a Rect
Path path_time = new Path(); //In constructor
textClock.getTextPath(time_text, 0, time_text.length(), 0f, 0f, path_time);
path_time.computeBounds(rect_time, true);

//[...]

textClock.getTextPath(time_text, 0, time_text.length(), offset_x - rect_time.left, offset_y, path_time);
canvas.drawPath(path_time, textClock);
```

**Comment by falzonv** [comment] 2024-11-16 10:00
Hello guys,

Thank you very much @kaanelloed for the fix and detailed explanation!

Sorry for the delayed feedback, the few programming I was able to find time for since August was mostly taken by internal work and tests to migrate the app from API 33 to API 34 (required to continue posting updates in Google Play).

I will merge your fix and it will be in the next update (probably in the coming weeks), thank you again for your help!

Best regards.

**Comment by falzonv** [comment] 2024-11-16 12:07
Oups, didn't meant to close it until it is effectively released...

**Comment by falzonv** [comment] 2024-12-15 16:59
Hello,

The new release v7.7.0 has been published few minutes ago!
I will leave this ticket open until it is available on F-Droid (usually takes 4 to 8 days).

Best regards.

**Comment by antodc** [comment] 2024-12-15 19:06
Wow! This is an amazing release. Thank you @falzonv and @kaanelloed for making so many improvements possible!

**Closed** 2024-12-22 10:22 UTC
Labels: solved, improvement request
