### ISSUE TITLE
Feature idea - Action when swiping past the bottom of the screen

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#155] opened 2021-11-22 18:19 UTC
Is it possible to have actions for swiping past the bottom of the screen, or upwards into the bottom of the screen?

(Like how settings are pulled down by dragging from above the top edge of the screen downwards)

**Comment by falzonv** [comment] 2021-11-28 17:35
Hello,

> Ability to swipe past bottom of screen to remove all apps in reversed mode

=> Hum, this looks like a duplicate of #154?
Unless I misunderstood both... could you please clarify which is which? :-)

> (Like how settings are pulled down by dragging from above the top edge of the screen downwards)

=> Sorry I do not understand this part: the settings windows (Appearance and Operation) do not have any special treatment, they use the default Android window management.
=> Do you mean to add animations to the open/close favorites/drawer actions? (if this case, I do not plan to do it ; #101)

Best regards.

**Comment by comradekingu** [comment] 2021-11-28 17:42
(Had me confused for a minute re-reading this ;)
I was thinking swiping from the outside of the screen was a different thing.
So you start outside the screen, and swipe upwards past the bottom.
That would mean it is always an available action, like pulling down the Android quick settings does the same from the top.

**Comment by falzonv** [comment] 2021-11-28 18:52
Thank you for the clarification, now I see what you mean :-)

Unfortunately this will not be possible because the system transfers this action only to the currently displayed app (incidentally, although this is difficult to reproduce, it seems to also be the case with swipes starting past the *edges* of the screen). An app running in background (not being the currently active app) would not receive the swipe.

If it was possible, it could also conflict with gesture navigation introduced in Android 10 that seems to make use of that part of the screen (https://www.androidauthority.com/android-10-gestures-1025113/).
Well, not with the firsts versions of Android 10 (#109), but this wouldn't be very future-proof anyway...

**Closed by falzonv** 2021-11-28 18:52 UTC
Labels: feature/improvement request, won't do/fix (see closure comment)
