### ISSUE TITLE
Duplicate Icons in favorites menu.

### ISSUE THREAD

**Issue by Pepper56** [falzonv/discreet-launcher#14] opened 2021-03-22 02:48 UTC
Since today, I now have a dozen copies of an app in  my favorites panel??

**Comment by falzonv** [comment] 2021-03-22 17:49
Hello,

Wow, that is strange!

Could you please give a little more details such as the following?
- The name of the app which is duplicated
- Your Android version and the version of the launcher (is it v1.2.0?)
- If this is v1.2.0, did you installed the launcher directly in this version or is it an update from a previous version? (\*)
- A screenshot may be useful

*(\*) This question is because there is a file format conversion between v1.1.0 and v1.2.0 to fix #3 and I wonder if this could be the reason.*

Best regards.

**Comment by falzonv** [comment] 2021-04-16 12:57
Hello,

Yesterday I received a mail from another user having this issue also in v2.6.0.
The duplicated application was HoloPlayer, but when testing on my phone I was not able to reproduce the issue.

If you are still using the launcher, here is an updated set of questions:
- What is your Android version? *(this information is available in settings of your phone, usually it is the last section and it has a name like "About the system" or something similar)*
- What is the name of the duplicated application?
- Is this application also duplicated in the applications drawer? Or only in the favorites panel?

Best regards.

**Comment by falzonv** [comment] 2021-04-17 07:19
Hello,

I made a try to solve this bug in release v3.0.2 by removing the file conversion introduced in v1.2.0 to avoid losing favorites when upgrading from previous versions.

This new release v3.0.2 has been pushed to the stores few minutes ago and the usual publishing delay is:

- 0 to 2 days for Google Play
- 4 to 8 days for F-Droid

Best regards.

**Comment by falzonv** [comment] 2021-04-27 10:50
This issue was definitely closed in v3.1.0 which is available since today on F-Droid.
I will close this ticket.

**Closed by falzonv** 2021-04-27 10:50 UTC
Labels: bug, solved
